export const DEFAULT_THEMES = [
"귀여움 과다 경보(Cutie Alert)",
"나 시크한 사람입니다만?(Chic But Confused)",
"은근 섹시 모먼트(Soft Sexy but PG-13)",
"머리카락이 나보다 주인공(Hair Is The Main Character)",
"햇빛이 나를 사랑함(Sunlight Crush Shot)",
"겨울잠 동물 같은 cozy vibe(Hibernation Mood)",
"립 강조인데 입술이 원하는 대로 움직이지 않음(Lip Drama)",
"레트로 무드(Retro)",
"침대와 한 몸이 된 나(Sleepy Icon)",
"따뜻한 조명 아래 나, 괜히 분위기 있어 보임(Warm Light Pretentiousness)",
"카메라 피하는데 더 잘 나오는 모순(Looking Away Superstar)",
"얼굴 반 가렸는데 왠지 더 신비로운 척(Half Hidden, Full Drama)",
"자연광 모먼트(Natural Light)",
"살짝 도도한 시티 무드(City Mood)",
"거울샷인데 배경이 더 주인공(Mirror Shot Photobomb)",
"블러샷인데 의도인지 실수인지 모름(Blurrrtiful)",
"실루엣인데 정체성이 사라진 나(Shadow Person)",
"음악 몰입샷(Music Makes Me Hot)",
"눈빛으로만 말해보자(Eyes Only Communication)",
"차가운 무드인데 손은 따뜻하게(Cool But Cold Hands)",
"은근 웃기고 은근 예쁜 미소(Mysteriously Cute Smile)",
"액세서리 90%, 나 10%(Accessory Steals The Show)",
"패션무드인데 실은 집 앞 편의점룩(Fashion But Not Really)",
"아련하게 찍었는데 사실 졸림(Drowsy Aesthetic)",
"올해의 베스트샷인데 찍다 폭소함(Best Portrait, But I Laughed)",
] as const;


